using System;
using ArchiveFlow.Domain.Entities;
using CommunityToolkit.Mvvm.ComponentModel;

namespace ArchiveFlow.App.ViewModels;

/// <summary>
/// Represents a single pending change generated by an action node preview.
/// Nothing is written until the user explicitly applies it.
/// </summary>
public partial class PendingChangeViewModel : ObservableObject
{
    public string Id { get; } = Guid.NewGuid().ToString("N");

    public FileRecord FileRecord { get; }

    public string FileName => FileRecord.FileName;

    public string ArchiveId => FileRecord.ArchiveId;

    public string SourceNodeTitle { get; }

    public string ChangeKind { get; }

    public string FieldName { get; }

    public string DisplayName { get; }

    public string FieldType { get; }

    public string Category { get; }

    public string OldValue { get; }

    public string NewValue { get; }

    public string SafetyLevel { get; }

    public bool CanApply { get; }

    [ObservableProperty]
    private string _status = "Pending";

    [ObservableProperty]
    private bool _isApplied;

    public PendingChangeViewModel(
        FileRecord fileRecord,
        string sourceNodeTitle,
        string changeKind,
        string fieldName,
        string displayName,
        string fieldType,
        string category,
        string oldValue,
        string newValue,
        string safetyLevel,
        bool canApply)
    {
        FileRecord = fileRecord;
        SourceNodeTitle = sourceNodeTitle;
        ChangeKind = changeKind;
        FieldName = fieldName;
        DisplayName = displayName;
        FieldType = fieldType;
        Category = category;
        OldValue = oldValue;
        NewValue = newValue;
        SafetyLevel = safetyLevel;
        CanApply = canApply;
    }

    public void MarkApplied()
    {
        IsApplied = true;
        Status = "Applied";
    }

    public void MarkSkipped(string reason)
    {
        IsApplied = false;
        Status = reason;
    }

    public void MarkFailed(string reason)
    {
        IsApplied = false;
        Status = $"Failed: {reason}";
    }
}
